insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (139, 177, 'TL', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (88, 55, 'Shadow', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (40, 171, 'Club Wagon', 14);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (95, 112, 'Landaulet', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (253, 191, 'Lancer Evolution', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (21, 13, 'Lancer', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (155, 5, '370Z', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (175, 156, 'A6', 15);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (246, 129, 'Justy', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (216, 190, 'Navigator L', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (296, 168, '612 Scaglietti', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (141, 89, 'Wrangler', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (172, 172, 'Frontier', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (179, 111, '928', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (131, 159, '3 Series', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (35, 164, 'MR2', 64);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 77, 'Caprice', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (39, 119, 'Golf', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (233, 144, 'SL-Class', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (243, 123, 'Accord', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (185, 160, 'Daytona', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (175, 147, 'Sentra', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (264, 158, 'LS Hybrid', 26);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (122, 96, 'Discovery', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (181, 37, 'Q5', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (192, 76, 'LeSabre', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 40, 'Century', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (55, 37, 'New Beetle', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (226, 157, 'Tucson', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (33, 41, 'Boxster', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (156, 52, 'Quest', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (212, 55, 'Ascender', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (287, 136, 'Prius', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (122, 189, 'Relay', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (44, 40, 'Carrera GT', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (149, 75, 'Grand Prix', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (111, 86, 'Firebird', 27);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (86, 124, 'LeSabre', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 23, 'Sequoia', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (5, 63, 'Odyssey', 99);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (27, 42, 'Panamera', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (40, 153, 'A6', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (286, 102, 'Esprit', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (263, 191, 'Cobalt SS', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (29, 179, 'Pilot', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (50, 146, 'C70', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (129, 135, 'Loyale', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (114, 161, 'MKS', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 86, 'G6', 12);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 73, 'Challenger', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (88, 197, 'Marauder', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (279, 108, 'CR-V', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (249, 186, 'Phaeton', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (109, 176, 'RAV4', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (154, 98, 'Cougar', 93);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (220, 189, 'S-Class', 92);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (128, 86, 'Monterey', 14);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (15, 75, 'Astro', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (287, 80, 'Azera', 27);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (8, 3, 'Bronco', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (289, 99, 'Escalade EXT', 42);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (39, 119, 'Expedition', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 7, 'SL-Class', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (65, 172, 'E250', 27);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 27, 'SLK-Class', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (165, 72, '5000CS', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (105, 191, 'Explorer', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (297, 180, 'Yukon', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (246, 181, 'Safari', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (166, 138, 'Explorer Sport', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (245, 114, 'Mazda6', 69);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (179, 142, 'Yukon', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (117, 73, '3 Series', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (34, 78, 'Sierra 1500', 99);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (154, 81, 'Marauder', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 37, 'Torino', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (192, 98, 'Mulsanne', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 74, 'M-Class', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (34, 2, 'Commander', 42);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (75, 184, 'Corvette', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (12, 172, 'Corvette', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 119, 'Grand Caravan', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (91, 181, 'Express 1500', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (190, 134, 'Horizon', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 17, 'Equator', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (109, 145, 'Cayenne', 99);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 102, '7 Series', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (222, 39, 'Corvette', 74);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (101, 117, 'B-Series', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (195, 13, 'Uplander', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (233, 104, 'Jimmy', 70);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (44, 14, 'Vandura 2500', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (63, 102, 'MX-5', 12);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (202, 131, 'Impala', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (83, 175, 'Jetta III', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (160, 184, 'Traverse', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (86, 155, 'Sierra 1500', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (179, 20, 'Caprice', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (86, 121, 'Solara', 64);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 146, 'Exige', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (66, 84, 'Entourage', 25);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (45, 121, 'Camry Hybrid', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (3, 157, 'Gemini', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (208, 21, 'G', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 1, '4Runner', 25);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (55, 44, 'Maxima', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (140, 76, 'Type 2', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (189, 54, '7 Series', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (175, 24, '5 Series', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (157, 25, 'Metro', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 45, 'Wrangler', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (298, 76, 'Firebird', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (146, 48, 'LTD Crown Victoria', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 10, 'S6', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (238, 107, 'Cabriolet', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (155, 138, 'Astro', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (179, 171, 'Sonata', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (28, 109, 'Tracker', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (203, 169, 'Ram Van B250', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (275, 74, 'Camry', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (62, 3, 'Escort ZX2', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 183, 'Reatta', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (257, 143, 'Sebring', 70);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 65, 'Corolla', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (219, 46, 'Mariner', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (56, 107, 'MKX', 15);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (77, 91, 'New Yorker', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (4, 16, 'Savana 1500', 9);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (59, 78, 'GLK-Class', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 89, 'S5', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (283, 178, 'S10', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (5, 149, 'Rodeo', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (5, 172, 'Elantra', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 141, 'TL', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (37, 58, 'Solstice', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 21, 'Armada', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (33, 155, 'Grand Caravan', 78);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (58, 190, 'Forester', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (49, 123, 'riolet', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (165, 50, 'Sprinter 3500', 91);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (93, 6, 'Ram Van 2500', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (114, 165, 'Boxster', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (187, 2, 'i-290', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (150, 170, '600SEL', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (78, 39, 'Tahoe', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (157, 68, 'Sonic', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (124, 79, 'Mountaineer', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (233, 177, 'Express 2500', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (257, 91, 'Zephyr', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (64, 22, 'Intrepid', 26);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (96, 107, 'F250', 42);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (290, 138, 'Spectra', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (253, 9, 'Monterey', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (272, 171, 'SJ 410', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (224, 91, 'Crown Victoria', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 39, 'MX-5', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 61, 'LTD Crown Victoria', 12);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (237, 198, '300M', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (149, 21, 'Excursion', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (157, 183, 'Carrera GT', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (8, 108, 'C70', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 108, '57', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (40, 182, 'G', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (287, 156, 'GX', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (202, 90, 'Silverado 3500', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (158, 162, 'Escalade EXT', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (206, 178, 'California', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (90, 25, 'QX56', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (215, 178, 'Sonata', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (12, 54, 'B-Series', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (68, 123, 'Avenger', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (190, 104, '500E', 42);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (50, 95, '1500 Club Coupe', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 176, 'Caravan', 12);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (105, 14, '968', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (59, 117, 'R-Class', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (181, 199, 'Pacifica', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 50, 'Dakota Club', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (109, 34, 'Golf', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (258, 50, 'A6', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (298, 63, 'Justy', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (196, 176, 'Tundra', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (211, 77, 'Bravada', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (120, 93, 'LX', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (252, 22, 'Sprinter 2500', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (266, 101, 'Continental GTC', 25);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (129, 162, 'Maxima', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (242, 133, 'Escort', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (195, 26, 'CTS', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 131, '300SL', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (20, 48, 'A5', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (264, 162, 'MPV', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 99, 'Envoy', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (233, 107, 'Cabriolet', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (227, 161, 'Tredia', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (273, 28, 'Prizm', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (21, 47, 'Firebird Formula', 13);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (266, 31, 'Chariot', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 155, 'Electra', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (111, 15, 'Suburban 2500', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (241, 139, 'Corvette', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 7, 'Matrix', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 9, 'Ram 1500', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (119, 82, 'Ghost', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (141, 4, 'Alcyone SVX', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (223, 9, 'Blazer', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (62, 62, 'VUE', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 52, 'Town Car', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (210, 36, 'Electra', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (130, 151, 'XC70', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (222, 21, 'Grand Marquis', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (89, 68, 'Sierra 1500', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (185, 119, 'S-Type', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (279, 88, 'Tucson', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 100, 'Outlook', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (104, 102, 'Intrigue', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (61, 90, 'V50', 70);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (87, 50, 'Malibu', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (9, 60, 'Cayman', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (52, 111, 'Ram Van 1500', 69);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (109, 42, 'Express 2500', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (154, 36, 'S10', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (172, 156, 'A6', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 159, 'E150', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (10, 175, 'Express', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 25, 'Reno', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (116, 21, 'Astro', 15);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (73, 132, 'LeBaron', 69);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (129, 146, 'Elantra', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (272, 95, 'Familia', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (70, 2, 'XJ', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (30, 65, 'Crosstour', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (181, 47, 'Savana 2500', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (284, 21, 'LeMans', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (117, 18, 'Camry', 64);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (33, 47, '929', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (202, 66, 'Riviera', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (294, 16, 'Expedition', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (211, 137, 'Cayman', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (38, 152, '164', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 41, 'S60', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 116, '626', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (29, 67, 'Suburban 1500', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (239, 108, 'LaCrosse', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 200, 'Sequoia', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (43, 2, 'Sportage', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (126, 74, 'Corvette', 86);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (180, 30, 'Civic', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (201, 193, 'Monterey', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (183, 182, 'Navigator', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 188, 'Swift', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (96, 69, 'Thunderbird', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (77, 191, 'Azera', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (243, 40, 'Routan', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (31, 120, 'SL-Class', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 139, 'Explorer', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (231, 199, 'Elantra', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (154, 107, 'Coachbuilder', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (79, 53, 'Sonoma', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (259, 175, 'C/V', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (95, 38, 'Taurus', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (7, 61, 'Century', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (190, 163, 'LX', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (210, 196, 'Spectra', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (71, 12, 'S10', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (116, 36, 'Cougar', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (106, 79, 'Lanos', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (252, 13, 'GX', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (30, 62, 'Esprit', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (239, 163, 'Pajero', 57);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (266, 71, 'Thunderbird', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 44, 'S10', 74);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (225, 58, 'Achieva', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (126, 54, 'CT', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (197, 7, 'Aerostar', 92);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 18, 'xB', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (233, 66, 'Passport', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 35, 'Trans Sport', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (15, 104, 'Wrangler', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (124, 83, 'G25', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (199, 154, 'Brooklands', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (62, 96, 'LS', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 2, 'Passat', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (150, 28, 'Regal', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (229, 158, 'ES', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 141, 'Range Rover', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (274, 22, '350Z', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (234, 102, 'Sunfire', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (118, 131, 'Vitara', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (219, 133, 'Monte Carlo', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (59, 24, 'A6', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 3, 'Jetta', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 22, 'Lancer Evolution', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (81, 47, 'D350', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (239, 18, 'Legacy', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (119, 198, 'Accent', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (79, 52, 'Xterra', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (296, 88, 'Forester', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (68, 177, 'Tacoma', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (234, 63, 'F-Series Super Duty', 69);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 86, 'Yukon', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (209, 121, 'Cayenne', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (1, 133, 'MX-5', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (250, 169, 'Fusion', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 143, 'Cabriolet', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (35, 2, 'Suburban 1500', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (196, 96, 'LeSabre', 26);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (34, 45, '944', 93);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (139, 23, 'ES', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (8, 32, 'Defender 90', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (5, 24, 'Yukon Denali', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (268, 172, 'Express 1500', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (215, 85, 'E-Class', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (194, 17, 'Jetta', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (58, 16, '928', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (183, 17, 'Outlook', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (269, 110, 'Aero 8', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (35, 200, 'Echo', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (166, 192, 'Grand Prix', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (104, 142, 'Challenger', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (103, 35, 'Corvette', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (47, 57, '1000', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (169, 75, 'Galant', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (209, 187, 'G-Series G30', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (275, 41, 'Suburban 1500', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (117, 64, 'F-Series Super Duty', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (116, 121, '9-5', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (93, 189, 'XC90', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (205, 123, 'Eldorado', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (8, 62, 'M-Class', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (56, 66, 'Rally Wagon G3500', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (258, 175, 'Dakota', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (26, 155, 'Malibu Maxx', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (289, 192, 'S4', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 158, 'Eclipse', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (227, 79, 'Civic', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (103, 143, 'Express 1500', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (113, 46, 'Bronco II', 74);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (157, 153, 'Challenger', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (31, 105, 'F150', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (128, 55, '2500', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (230, 18, 'Element', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 47, 'Verano', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (90, 99, 'Camaro', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (94, 135, 'Avanti', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (260, 53, 'Highlander', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (179, 20, 'Escort', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (257, 80, 'Alero', 26);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (104, 112, 'Caravan', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (129, 95, 'Echo', 91);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (111, 56, 'M3', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (24, 92, 'FJ Cruiser', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 48, 'GS', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (226, 43, 'SL-Class', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (71, 161, 'Breeze', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (115, 8, 'Forester', 9);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (89, 148, 'GL-Class', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (107, 81, 'Camry', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (121, 129, 'Fox', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (205, 48, '100', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (108, 97, 'Blazer', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 75, 'Montero Sport', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (96, 200, 'F-Series', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (45, 105, 'Tahoe', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (259, 173, 'Regal', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (26, 190, 'S-Series', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (6, 135, 'Coachbuilder', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (297, 198, 'B-Series', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (202, 82, 'Truck', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 63, 'Alcyone SVX', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (175, 153, 'Grand Am', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (69, 27, 'Tacoma', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (86, 49, 'Corvette', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (287, 53, 'Cherokee', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (241, 151, '88', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (68, 18, 'Sebring', 86);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (236, 151, 'Prowler', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (79, 167, 'Truck', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (49, 85, 'Maxima', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (197, 170, 'Type 2', 86);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 192, '911', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (34, 172, 'PT Cruiser', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (70, 96, 'Elantra', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 152, 'A4', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (278, 92, 'C70', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (157, 11, 'Express 2500', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (32, 71, 'Thunderbird', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (214, 154, 'Ranger', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (222, 117, 'Rendezvous', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (29, 69, 'Intrepid', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 55, 'XLR', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 177, 'SL-Class', 13);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (227, 153, '3 Series', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (300, 5, 'Bronco', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (113, 106, 'E350', 42);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 29, 'B-Series', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (84, 71, 'Mustang', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (175, 181, 'Cavalier', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (49, 110, 'Mystique', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (34, 110, 'Tribeca', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (270, 92, 'Monte Carlo', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (217, 26, 'Gallardo', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (39, 142, 'Parisienne', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (13, 144, 'Express', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (217, 142, 'Q', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (55, 127, 'Sierra 3500', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (100, 98, 'Riviera', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (50, 26, 'tC', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (188, 158, 'Jetta', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (39, 5, '900', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 107, '323', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (15, 64, 'Elantra', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (61, 53, 'Quest', 86);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (16, 124, 'Baja', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (245, 8, '240SX', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (33, 128, '626', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (184, 105, 'S60', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (217, 38, 'Outlook', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (299, 70, 'Sable', 9);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (222, 86, 'Esteem', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (104, 141, 'SC', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (181, 137, 'Hombre', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (24, 38, 'Yukon', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (61, 189, 'Accord', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (162, 155, 'M6', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (146, 94, 'Range Rover', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (140, 35, 'Cruze', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (294, 8, 'MX-3', 27);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (198, 6, '350Z', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (130, 125, 'Tundra', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (195, 131, 'Excursion', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (78, 17, 'Ram 1500', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (193, 80, 'Blazer', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (225, 119, 'Starion', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (281, 155, 'Sunbird', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (118, 177, 'Rendezvous', 27);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (19, 6, 'H3', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (124, 96, 'Taurus', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (283, 168, 'Silverado 3500', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (296, 6, 'MX-5', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (283, 45, 'Windstar', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (40, 41, 'Quest', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (183, 140, 'Galant', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (113, 106, 'Tracker', 92);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (234, 95, 'SSR', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (234, 51, 'Grand Marquis', 57);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 179, 'Econoline E250', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 123, 'R-Class', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 85, 'Bonneville', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (53, 155, 'Th!nk', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 152, 'Navajo', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (229, 200, 'Grand Vitara', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 39, 'H2 SUV', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (70, 146, 'Endeavor', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 150, 'GX', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (73, 58, 'Familia', 14);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (85, 75, 'Familia', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (33, 114, 'Quest', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (60, 168, '207', 42);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 45, 'V40', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (259, 75, 'Cooper', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (196, 172, 'Justy', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (199, 198, 'Silhouette', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 12, 'Century', 93);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (124, 108, 'Grand Cherokee', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (232, 129, 'Vigor', 69);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (262, 153, 'GTO', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 124, 'F-Series Super Duty', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (131, 61, 'Supra', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (166, 74, 'Ram', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (81, 84, 'Tundra', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (298, 146, 'Suburban 2500', 13);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (9, 166, 'Outlander', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (276, 118, 'CL-Class', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (284, 53, 'Seville', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (162, 84, 'Jetta', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (251, 146, 'Escort ZX2', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (184, 23, '350Z', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (272, 74, 'Explorer Sport Trac', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (228, 147, 'Equus', 99);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (67, 169, 'Ram Van B250', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 102, 'Optima', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (20, 90, 'LS', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (85, 45, 'Integra', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (58, 94, 'Fusion', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (239, 25, 'Montero Sport', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (246, 2, 'Continental Mark VII', 25);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 136, 'Sonata', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (119, 37, '1000', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (217, 8, 'Mariner', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (150, 164, 'Freelander', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (41, 168, 'Evora', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (153, 165, 'Range Rover Sport', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (82, 177, 'D150', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (263, 97, 'Avalon', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (55, 113, 'MX-6', 74);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (79, 171, 'Eclipse', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (209, 34, 'X6', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (78, 112, 'Ram 3500', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (243, 116, '9-5', 58);
